CREATE TABLE status (name PRIMARY KEY, status, twitter, youtube, twitch, reddit);
CREATE TABLE activity (datetime, name);
CREATE TABLE joins(date, name, UUID, IP);
CREATE TABLE achievements (ts, name, achievement);
CREATE TABLE loglag (ts, ticks);
CREATE TABLE location (datetime DEFAULT CURRENT_TIMESTAMP, UUID, dim, x, y, z);
CREATE TABLE process (ts DEFAULT CURRENT_TIMESTAMP, process, id, end);
CREATE TABLE stats (datetime DEFAULT CURRENT_TIMESTAMP, UUID, stats);
CREATE TABLE whitelist (name, UUID, ts default CURRENT_TIMESTAMP, UNIQUE(UUID));
CREATE TABLE playeractivity (datetime DEFAULT CURRENT_TIMESTAMP, UUID, dim, x, y, z, invadded, invremoved, stats);
CREATE TABLE chestactivity (datetimestart TIMESTAMP, datetimeend TIMESTAMP, dim, x, y, z, diff);
CREATE TABLE discordverify (name PRIMARY KEY, token, discordid);
CREATE TABLE players (UUID PRIMARY KEY, name, discordID, lastIP, country);
CREATE TABLE verify (datetime DEFAULT CURRENT_TIMESTAMP, name, discordID);
CREATE TABLE maildrop (coords primary key, name, desc, slots, hidden, inverted, notified, datetime);
CREATE TABLE "chestactivityold" (datetime TIMESTAMP, dim, x, y, z, chest);
CREATE TABLE "pois" (coords primary key, type, text1, text2, text3);
CREATE TABLE "polylines" (dim, color, id, coords);
CREATE TABLE "flyway" (dim, coords, text1, text2, code, destination);
CREATE TABLE "chestactivitynew" (datetime TIMESTAMP, dim, x, y, z, chest);
CREATE TABLE temppois (coords primary key, type, text1, text2, text3);
CREATE TABLE temppolylines (dim, color, id, coords);
CREATE TABLE tempflyway (dim, coords, text1, text2, code, destination);
CREATE TABLE tempchestactivity (datetime TIMESTAMP, dim, x, y, z, chest);
CREATE VIEW onlineplayers as select name from activity where datetime >= DATETIME("now", "-2 minutes") group by name;
CREATE VIEW playerUUID as select name, UUID from (select * from joins order by date asc) group by UUID;
